name: n_sneaker_app
description: N Sneaker App for iOS and Android
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+18

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  algolia: ^1.0.4
  another_flushbar: 1.10.28 # 1.10.29はFlutter3.0.0でエラー
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.9
  cloud_functions: ^3.2.9
  crypto: ^3.0.1
  dismissible_page: ^0.7.2
  easy_debounce: ^2.0.2+1
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.0
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  flutter_unity_widget: 2020.3.25
  google_sign_in: ^5.2.4
  hooks_riverpod: ^1.0.3
  image_gallery_saver: ^1.7.1
  infinite_scroll_pagination: ^3.1.0
  introduction_screen: ^3.0.2
  model_viewer_plus: ^1.2.0
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9
  purchases_flutter: ^3.10.0
  shared_preferences: ^2.0.9
  sign_in_with_apple: ^4.0.0
  social_login_buttons: ^1.0.6+2
  url_launcher: ^6.0.20

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Black.otf
        - asset: fonts/NotoSansJP-Bold.otf
        - asset: fonts/NotoSansJP-Light.otf
        - asset: fonts/NotoSansJP-Medium.otf
        - asset: fonts/NotoSansJP-Regular.otf
        - asset: fonts/NotoSansJP-Thin.otf

  assets:
    - assets/collection_background/
    - assets/launcher_icon/
    - assets/onboarding_images/
    - assets/sign_up_reward/

flutter_icons:
  android: true
  ios: true
