name: n_sneaker_app
description: N Sneaker App for iOS and Android
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.9
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.0
  flutter:
    sdk: flutter
  flutter_unity_widget: 2020.3.25
  hooks_riverpod: ^1.0.3
  native_screenshot: ^1.0.0
  package_info_plus: ^1.4.0
  share_plus: ^3.1.0

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
