name: n_sneaker_app
description: N Sneaker App for iOS and Android
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  adapty_flutter: ^1.0.9
  algolia: ^1.0.4
  another_flushbar: ^1.10.28
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.9
  cloud_functions: ^3.2.9
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.0
  flutter:
    sdk: flutter
  flutter_unity_widget: 2020.3.25
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  infinite_scroll_pagination: ^3.1.0
  model_viewer_plus: ^1.1.2
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.9
  social_login_buttons: ^1.0.6+2
  url_launcher: ^6.0.20

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  fonts:
    - family: MPLUS1
      fonts:
        - asset: fonts/MPLUS1-Black.ttf
        - asset: fonts/MPLUS1-Bold.ttf
        - asset: fonts/MPLUS1-ExtraBold.ttf
        - asset: fonts/MPLUS1-ExtraLight.ttf
        - asset: fonts/MPLUS1-Light.ttf
        - asset: fonts/MPLUS1-Medium.ttf
        - asset: fonts/MPLUS1-Regular.ttf
        - asset: fonts/MPLUS1-SemiBold.ttf
        - asset: fonts/MPLUS1-Thin.ttf

  assets:
    - assets/launcher_icon/icon.jpg

flutter_icons:
  android: true
  ios: true
